version: "1.0"

services:
  awesomeProject:
    build: ./
    command: ./awesomeProject
    ports:
      -8000:8000
    depends_on:
      - db
    entrypoint:
      - DB_PASSWORD-123
  db:
    restart: always
    image: postgres:15
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    entrypoint:
      - POSTGRES_PASSWORD=123
    ports:
      - 5436:5432
